apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: todo-web-application
  name: todo-web-application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: todo-web-application
    spec:
      containers:
      - env:
        - name: RDS_DB_NAME
          #value: todos
          valueFrom:
            conigMapKeyRef:
              name: todo-web-application-config
              key: RDS_DB_NAME
        - name: RDS_HOSTNAME
          #value: mysql
          valueFrom:
            conigMapKeyRef:
              name: todo-web-application-config
              key: RDS_HOSTNAME
        - name: RDS_PASSWORD
          #value: dummytodos
          valueFrom:
            secretKeyRef:
              name: todo-web-application-secrets
              key: RDS_PASSWORD
        - name: RDS_PORT
          #value: "3306"
          valueFrom:
            conigMapKeyRef:
              name: todo-web-application-config
              key: RDS_PORT
        - name: RDS_USERNAME
          #value: todos-user
          valueFrom:
            conigMapKeyRef:
              name: todo-web-application-config
              key: RDS_USERNAME
        image: in28min/todo-web-application-mysql:0.0.1-SNAPSHOT
        name: todo-web-application
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 8080
      restartPolicy: Always
